# Generated by Django 3.2 on 2022-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_historicaltranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranslation',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translation',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
