# Generated by Django 3.2 on 2022-11-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_auto_20221124_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltranslation',
            name='mark',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='translation',
            name='mark',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
