# Generated by Django 3.2 on 2023-01-26 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0007_auto_20230126_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltranslation',
            name='user_qa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='user_translator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translation',
            name='user_qa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translation',
            name='user_translator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
